config/routes.rb
Assogwada::Application.routes.draw do
  devise_for :users

  resources :newsletters
  
  resources :mailings
  
  resources :quests

  resources :conventions

  resources :associations_champ_interventions

  resources :conv_pluris

  resources :dispositifs do
    resources :regroupements
  end

  resources :plannings
  
  resources :associations do
    collection do
      get 'add_ci'
      get 'inscription'
      get 'download_quest'
      get 'test_exception'
      get 'accueil'
      get 'verify'
      get 'export_xls_csv'
      get 'incomplete'
      get 'form_abonnement'
      post 'remove_ci'
      post 'envoi'
      post 'envoi_inscription'
      post 'envoi_formabonnement'
      post 'newsletter'
    end
    member do
      put 'accept'
      put 'reject'
      put 'unsuspend'
      put 'suspend'
    end
    resources :salaries, :singular => 'salarie'
    resources :locals
    resources :besoin_humains
    resources :besoin_materiels
    resources :activites
    resources :regroupements
    resources :dispositifs
    resources :agrements
    resources :orgahabs
    resources :adhesions
    resources :assoc_manifs
    resources :manifestations
    resources :assoc_champintervs
    resources :champ_interventions
    resources :membres
    resources :conseiladmins
    resources :conv_pluris
  end
  
  resources :conseiladmins do
    resources :presidents
    resources :premier_vicepresidents
    resources :second_vicepresidents
    resources :secretaires
    resources :secretaire_adjoints
    resources :tresoriers
    resources :tresorier_adjoints
    resources :membres
  end
  
  resources :regroupements

  resources :agrements

  resources :orgahabs do
    resources :agrements
    resources :conv_pluris
  end

  resources :adhesions

  resources :assoc_manifs

  resources :membres

  resources :manifestations do
    resources :associations
  end

  resources :champ_interventions

  resources :salaries, :singular => 'salarie'

  resources :activites do
    resources :plannings
  end

  resources :besoin_materiels
  
  resources :besoin_humains
  
  resources :locals
  
  resources :users
    

  resource :recherches do
    collection do
      get 'liste'
      post 'commune'
      get 'export_result'
      get 'export_excel'
    end
  end

  match '/recherch/:id' => 'recherches#show', :as => 'recherch'
   
  match '/demande_abonnement', :controller => 'associations', :action => 'form_abonnement'
  
  
  

  root :to => 'associations#accueil'

  match ':controller/service.wsdl', :action => 'wsdl'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/quest.rb
# -*- encoding : utf-8 -*-
class Quest < ActiveRecord::Base
  validates_presence_of :nom, :nom_asso, :on => :create, :message => "ne peut être vide"
  
  protected
  
  def upload_questionnaire=(questionnaire_field)
    unless questionnaire_field.blank?
      self.filename = base_part_of(questionnaire_field.original_filename)
      self.file_url = "#{RAILS_ROOT}/questionnaires/" + self.nom_asso + "_" + filename  
      self.content_type = questionnaire_field.content_type.chomp
      # écriture du fichier
      f1 = File.new(self.file_url, "wb")
      f1.write(questionnaire_field.read)
      f1.close
    end
  end
  
  def base_part_of(file_name)
    File.basename(file_name).gsub(/[^\w._-]/, '')
  end
end

app/controllers/quests_controller.rb
# -*- encoding : utf-8 -*-
class QuestsController < ApplicationController
  # GET /quests
  # GET /quests.xml
  def index
    @quests = Quest.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quests }
    end
  end

  # GET /quests/1
  # GET /quests/1.xml
  def show
    @quest = Quest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quest }
    end
  end

  # GET /quests/new
  # GET /quests/new.xml
  def new
    @quest = Quest.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quest }
    end
  end

  # GET /quests/1/edit
  def edit
    @quest = Quest.find(params[:id])
  end

  # POST /quests
  # POST /quests.xml
  def create
    @quest = Quest.new(params[:quest])

    respond_to do |format|
      if @quest.save
        flash[:notice] = "Le questionnaire et les informations d'envoi ont bien été enregistré."
        format.html { redirect_to(@quest) }
        format.xml  { render :xml => @quest, :status => :created, :location => @quest }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quests/1
  # PUT /quests/1.xml
  def update
    @quest = Quest.find(params[:id])

    respond_to do |format|
      if @quest.update_attributes(params[:quest])
        flash[:notice] = "Les informations concernant l'envoi de ce questionnaire ont été mis à jour."
        format.html { redirect_to(@quest) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.xml
  def destroy
    @quest = Quest.find(params[:id])
    @quest.destroy

    respond_to do |format|
      format.html { redirect_to(quests_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/quests_helper.rb
# -*- encoding : utf-8 -*-
module QuestsHelper
end

app/views/quests/edit.html.erb
<h1>Modification Données d'envoi de questionnaire</h1>

<%= error_messages_for :quest %>

<% form_for(@quest) do |f| %>
  <p>
    <b>Nom</b><br />
    <%= f.text_field :nom %>
  </p>

  <p>
    <b>Nom asso</b><br />
    <%= f.text_field :nom_asso %>
  </p>

  <p>
    <b>File url</b><br />
    <%= f.text_field :file_url %>
  </p>

  <p>
    <b>Content type</b><br />
    <%= f.text_field :content_type %>
  </p>

  <p>
    <b>Filename</b><br />
    <%= f.text_field :filename %>
  </p>

  <p>
    <%= f.submit "Mettre à Jour" %>
  </p>
<% end %>

<%= link_to 'Voir', @quest %> |
<%= link_to 'Retour', quests_path %>

app/views/quests/index.html.erb
<h1>Listing des questionnaires envoyés</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Nom asso</th>
    <th>File url</th>
    <th>Content type</th>
    <th>Filename</th>
  </tr>

<% for quest in @quests %>
  <tr>
    <td><%=h quest.nom %></td>
    <td><%=h quest.nom_asso %></td>
    <td><%=h quest.file_url %></td>
    <td><%=h quest.content_type %></td>
    <td><%=h quest.filename %></td>
    <td><%= link_to 'Voir', quest %></td>
    <td><%= link_to 'Modifier', edit_quest_path(quest) %></td>
    <td><%= link_to 'Supprimer', quest, :confirm => 'Êtes vous sur ?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouveau questionnaire à envoyer', new_quest_path %>

app/views/quests/new.html.erb
<h1>Enregistrement Infos sur Questionnaire envoyé</h1>

<%= error_messages_for :quest %>

<% form_for(@quest) do |f| %>
  <p>
    <b>Nom</b><br />
    <%= f.text_field :nom %>
  </p>

  <p>
    <b>Nom asso</b><br />
    <%= f.text_field :nom_asso %>
  </p>

  <p>
    <b>File url</b><br />
    <%= f.text_field :file_url %>
  </p>

  <p>
    <b>Content type</b><br />
    <%= f.text_field :content_type %>
  </p>

  <p>
    <b>Filename</b><br />
    <%= f.text_field :filename %>
  </p>

  <p>
    <%= f.submit "Enregistrer" %>
  </p>
<% end %>

<%= link_to 'Retour', quests_path %>

app/views/quests/show.html.erb
<p>
  <b>Nom:</b>
  <%=h @quest.nom %>
</p>

<p>
  <b>Nom asso:</b>
  <%=h @quest.nom_asso %>
</p>

<p>
  <b>File url:</b>
  <%=h @quest.file_url %>
</p>

<p>
  <b>Content type:</b>
  <%=h @quest.content_type %>
</p>

<p>
  <b>Filename:</b>
  <%=h @quest.filename %>
</p>


<%= link_to 'Modifier', edit_quest_path(@quest) %> |
<%= link_to 'Retour', quests_path %>