config/routes.rb
Assogwada::Application.routes.draw do
  devise_for :users

  resources :newsletters
  
  resources :mailings
  
  resources :quests

  resources :conventions

  resources :associations_champ_interventions

  resources :conv_pluris

  resources :dispositifs do
    resources :regroupements
  end

  resources :plannings
  
  resources :associations do
    collection do
      get 'add_ci'
      get 'inscription'
      get 'download_quest'
      get 'test_exception'
      get 'accueil'
      get 'verify'
      get 'export_xls_csv'
      get 'incomplete'
      get 'form_abonnement'
      post 'remove_ci'
      post 'envoi'
      post 'envoi_inscription'
      post 'envoi_formabonnement'
      post 'newsletter'
    end
    member do
      put 'accept'
      put 'reject'
      put 'unsuspend'
      put 'suspend'
    end
    resources :salaries, :singular => 'salarie'
    resources :locals
    resources :besoin_humains
    resources :besoin_materiels
    resources :activites
    resources :regroupements
    resources :dispositifs
    resources :agrements
    resources :orgahabs
    resources :adhesions
    resources :assoc_manifs
    resources :manifestations
    resources :assoc_champintervs
    resources :champ_interventions
    resources :membres
    resources :conseiladmins
    resources :conv_pluris
  end
  
  resources :conseiladmins do
    resources :presidents
    resources :premier_vicepresidents
    resources :second_vicepresidents
    resources :secretaires
    resources :secretaire_adjoints
    resources :tresoriers
    resources :tresorier_adjoints
    resources :membres
  end
  
  resources :regroupements

  resources :agrements

  resources :orgahabs do
    resources :agrements
    resources :conv_pluris
  end

  resources :adhesions

  resources :assoc_manifs

  resources :membres

  resources :manifestations do
    resources :associations
  end

  resources :champ_interventions

  resources :salaries, :singular => 'salarie'

  resources :activites do
    resources :plannings
  end

  resources :besoin_materiels
  
  resources :besoin_humains
  
  resources :locals
  
  resources :users
    

  resource :recherches do
    collection do
      get 'liste'
      post 'commune'
      get 'export_result'
      get 'export_excel'
    end
  end

  match '/recherch/:id' => 'recherches#show', :as => 'recherch'
   
  match '/demande_abonnement', :controller => 'associations', :action => 'form_abonnement'
  
  
  

  root :to => 'associations#accueil'

  match ':controller/service.wsdl', :action => 'wsdl'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/mailing.rb
# -*- encoding : utf-8 -*-
class Mailing < ActiveRecord::Base
  
  def deliver(associations)
    QuestMailer.deliver_mailing(associations, self)
    update_attribute(:published_at, Time.now)
  end
  
end

app/controllers/mailings_controller.rb
# -*- encoding : utf-8 -*-
class MailingsController < ApplicationController
  
  before_filter :login_required
  
  # GET /mailings
  # GET /mailings.xml
  def index
    @mailings = Mailing.paginate(:page => params[:page], :per_page => 20,
     :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mailings }
    end
  end

  # GET /mailings/1
  # GET /mailings/1.xml
  def show
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mailing }
    end
  end

  # GET /mailings/new
  # GET /mailings/new.xml
  def new
    @mailing = Mailing.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mailing }
    end
  end
  
  # GET /mailings/1/edit
  def edit
    @mailing = Mailing.find(params[:id])
  end

  # POST /mailings
  # POST /mailings.xml
  def create
    @mailing = Mailing.new(params[:mailing])
    resultats = []
 
    if session[:resultats].nil?
      associations = Association.find(:all, :select => "id, nom, permalink")
      associations.each do |association|
        resultats << association.id
      end
    else
      session[:resultats].each do |id_nom|
        resultats << id_nom[0]
      end
    end
    
    respond_to do |format|
      if @mailing.save
        @mailing.send_later(:deliver)
        flash[:notice] = "Mailing en cours d'envoi …"
         session[:resultats] = nil
        format.html { redirect_to(mailings_url) }
        format.xml  { render :xml => @mailing, :status => :created, :location => @mailing }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mailing.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def reexpedition
    @mailing = Mailing.find(params[:id])
    call_rake(:send_mailing, :mailing_id => @mailing.id.to_i)
    
    respond_to do |format|
      flash[:notice] = "Mailing en cours d'envoi …"
      format.html { redirect_to mailings_url }
    end
  end
  
  # PUT /mailings/1
  # PUT /mailings/1.xml
  def update
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      if @mailing.update_attributes(params[:mailing])
        flash[:notice] = 'Mailing was successfully updated.'
        format.html { redirect_to(@mailing) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mailing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mailings/1
  # DELETE /mailings/1.xml
  def destroy
    @mailing = Mailing.find(params[:id])
    @mailing.destroy

    respond_to do |format|
      format.html { redirect_to(mailings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/mailings_helper.rb
# -*- encoding : utf-8 -*-
module MailingsHelper
end

app/views/mailings/edit.html.erb
<div id="side-colonne">
  <div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></p>
		<p>
			<b>Recherche rapide</b><br/>
			<% form_tag associations_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %><br/><br/>
				<%= submit_tag "Trouver", :name => nil %>
			<% end %>
		</p>
		<p class="to_valid">
			À valider : <%= @nb_to_verify %><br/>
			<%= validation_links(@nb_to_verify) %>
		</p>
		<p><%= link_to 'Ajouter une association', new_association_path %></p>
		<% unless @last_recorded.nil? %>
		<p>
			Dernière association reférencée :<br/>
			<%= link_to  @last_recorded.nom, association_path(@last_recorded)  %><br/>
			le <%= h @last_recorded.created_at.strftime("%d/%m/%Y") %>
		</p>
		<% end %>
		<p>
			Nombre d'associations enregistrées : <strong><%=h Association.count %></strong><br/>
		</p>
		<p class="export_csv">
			<%= link_to "Export Excel", formatted_export_xls_csv_associations_url(:xls) %><br/>
			<%= link_to "Export CSV", formatted_export_xls_csv_associations_url(:csv) %><br/>
			<%= link_to "Gestion des Mailings", mailings_path() %><br/>
			<%= link_to "Gestion des Newsletters", newsletters_path() %>
		</p>
		<p class="to_valid">
			Assos incomplètes : <%= @asso_incomplete %><br/>
			<%= link_to "Voir", incomplete_associations_path() %>
		</p>
		<p>
			<%= link_to "Ajouter un champ d'intervention", new_champ_intervention_path() %>
		</p>
	</div>
</div>

<div id="colonne1">
<h2 class="ficheid">Modifier le mailing</h2>

<%= error_messages_for :mailing %>

<% form_for(@mailing) do |f| %>
  <p>
    <b>Objet</b><br />
    <%= f.text_field :objet %>
  </p>

  <p>
    <b>Body</b><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit "Mettre à jour" %>
  </p>
<% end %>

<%= link_to 'Voir', @mailing %> |
<%= link_to 'Retour', mailings_path %>
</div>

app/views/mailings/index.html.erb
<div id="side-colonne">
  <div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></p>
		<p>
			<b>Recherche rapide</b><br/>
			<% form_tag associations_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %><br/><br/>
				<%= submit_tag "Trouver", :name => nil %>
			<% end %>
		</p>
		<p class="to_valid">
			À valider : <%= @nb_to_verify %><br/>
			<%= validation_links(@nb_to_verify) %>
		</p>
		<p><%= link_to 'Ajouter une association', new_association_path %></p>
		<% unless @last_recorded.nil? %>
		<p>
			Dernière association reférencée :<br/>
			<%= link_to  @last_recorded.nom, association_path(@last_recorded)  %><br/>
			le <%= h @last_recorded.created_at.strftime("%d/%m/%Y") %>
		</p>
		<% end %>
		<p>
			Nombre d'associations enregistrées : <strong><%=h Association.count %></strong><br/>
		</p>
		<p class="export_csv">
			<%= link_to "Export Excel", formatted_export_xls_csv_associations_url(:xls) %><br/>
			<%= link_to "Export CSV", formatted_export_xls_csv_associations_url(:csv) %><br/>
			<%= link_to "Gestion des Mailings", mailings_path() %><br/>
			<%= link_to "Gestion des Newsletters", newsletters_path() %>
		</p>
		<p class="to_valid">
			Assos incomplètes : <%= @asso_incomplete %><br/>
			<%= link_to "Voir", incomplete_associations_path() %>
		</p>
		<p>
			<%= link_to "Ajouter un champ d'intervention", new_champ_intervention_path() %>
		</p>
	</div>
</div>

<div id="colonne1">
  <h2 class="ficheid">Listing des mailings</h2>

  <table>
    <tr>
      <th>Objet</th>
      <th>Corps du Texte</th>
      <th>Envoyé le</th>
    </tr>

  <% for mailing in @mailings %>
    <tr>
      <td><%=h mailing.objet %></td>
      <td><%=h truncate(mailing.body, 30) %></td>
      <td><%=h mailing.published_at.strftime("%d/%m/%Y") if mailing.published_at %></td>
      <td><%= link_to 'Voir', mailing %></td>
      <td><%= link_to 'Modifier', edit_mailing_path(mailing) %></td>
      <td><%= link_to "Ré-expédier", reexpedition_mailing_path(mailing) %></td>
      <td><%= link_to 'X', mailing, :confirm => 'Êtes vous certain ?', :method => :delete, :alt => "supprimer" %></td>
    </tr>
  <% end %>
  </table>

  <br />
  <%= will_paginate @mailings %>
  
  <p>
    <%= link_to "Rédiger un Mailing ciblé", new_recherch_path() %> | <%= link_to "Envoyer un Mailing général", new_mailing_path() %>
  </p>
</div>

app/views/mailings/new.html.erb
<div id="side-colonne">
	<div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></p>
		<p>
			<b>Recherche rapide</b><br/>
			<% form_tag associations_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %><br/><br/>
				<%= submit_tag "Trouver", :name => nil %>
			<% end %>
		</p>
		<p class="to_valid">
			À valider : <%= @nb_to_verify %><br/>
			<%= validation_links(@nb_to_verify) %>
		</p>
		<p><%= link_to 'Ajouter une association', new_association_path %></p>
		<% unless @last_recorded.nil? %>
		<p>
			Dernière association reférencée :<br/>
			<%= link_to  @last_recorded.nom, association_path(@last_recorded)  %><br/>
			le <%= h @last_recorded.created_at.strftime("%d/%m/%Y") %>
		</p>
		<% end %>
		<p>
			Nombre d'associations enregistrées : <strong><%=h Association.count %></strong><br/>
		</p>
		<p class="export_csv">
			<%= link_to "Export Excel", formatted_export_xls_csv_associations_url(:xls) %><br/>
			<%= link_to "Export CSV", formatted_export_xls_csv_associations_url(:csv) %><br/>
			<%= link_to "Gestion Mailings", mailings_path() %><br/>
			<%= link_to "Gestion des Newsletters", newsletters_path() %>
		</p>
		<p class="to_valid">
			Assos incomplètes : <%= @asso_incomplete %><br/>
			<%= link_to "Voir", incomplete_associations_path() %>
		</p>
		<p>
			<%= link_to "Ajouter un champ d'intervention", new_champ_intervention_path() %>
		</p>
	</div>
</div>

<div id="colonne1">
  <h2 class="ficheid">Rédigez votre mailing</h2>
  
  <p>
    Vous pouvez rédiger ici, le courrier à envoyer aux associations sélectionnées par l'outil de recherche.
  </p>

  <%= error_messages_for :mailing %>

  <% form_for(@mailing) do |f| %>
    <p>
      <b>Objet</b><br />
      <%= f.text_field :objet, :size => 40 %>
    </p>

    <p>
      <b>Body</b><br />
      <%= f.text_area :body, :cols => 40, :rows => 20 %>
    </p>

    <p>
      <%= f.submit "Envoyer le mailing" %>
    </p>
  <% end %>

  <%= link_to 'Retour', mailings_path %>
</div>

app/views/mailings/show.html.erb
<div id="side-colonne">
  <div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></p>
		<p>
			<b>Recherche rapide</b><br/>
			<% form_tag associations_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %><br/><br/>
				<%= submit_tag "Trouver", :name => nil %>
			<% end %>
		</p>
		<p class="to_valid">
			À valider : <%= @nb_to_verify %><br/>
			<%= validation_links(@nb_to_verify) %>
		</p>
		<p><%= link_to 'Ajouter une association', new_association_path %></p>
		<% unless @last_recorded.nil? %>
		<p>
			Dernière association reférencée :<br/>
			<%= link_to  @last_recorded.nom, association_path(@last_recorded)  %><br/>
			le <%= h @last_recorded.created_at.strftime("%d/%m/%Y") %>
		</p>
		<% end %>
		<p>
			Nombre d'associations enregistrées : <strong><%=h Association.count %></strong><br/>
		</p>
		<p class="export_csv">
			<%= link_to "Export Excel", formatted_export_xls_csv_associations_url(:xls) %><br/>
			<%= link_to "Export CSV", formatted_export_xls_csv_associations_url(:csv) %><br/>
			<%= link_to "Gestion des Mailings", mailings_path() %><br/>
			<%= link_to "Gestion des Newsletters", newsletters_path() %>
		</p>
		<p class="to_valid">
			Assos incomplètes : <%= @asso_incomplete %><br/>
			<%= link_to "Voir", incomplete_associations_path() %>
		</p>
		<p>
			<%= link_to "Ajouter un champ d'intervention", new_champ_intervention_path() %>
		</p>
	</div>
</div>

<div id="colonne1">
  <h2 class="ficheid">Newsletter</h2>
  
  <p>
    <b>Objet:</b>
    <%=h @mailing.objet %>
  </p>

  <p>
    <b>Contenu :</b>
    <%=h @mailing.body %>
  </p>

  <p>
    <b>Envoyé le :</b>
    <%#h @mailing.published_at.strftime("%d/%m/%Y") %>
  </p>

  <%= link_to 'Modifier', edit_mailing_path(@mailing) %> |
  <%= link_to 'Retour', mailings_path %>
</div>