config/routes.rb
Assogwada::Application.routes.draw do
  devise_for :users

  resources :newsletters
  
  resources :mailings
  
  resources :quests

  resources :conventions

  resources :associations_champ_interventions

  resources :conv_pluris

  resources :dispositifs do
    resources :regroupements
  end

  resources :plannings
  
  resources :associations do
    collection do
      get 'add_ci'
      get 'inscription'
      get 'download_quest'
      get 'test_exception'
      get 'accueil'
      get 'verify'
      get 'export_xls_csv'
      get 'incomplete'
      get 'form_abonnement'
      post 'remove_ci'
      post 'envoi'
      post 'envoi_inscription'
      post 'envoi_formabonnement'
      post 'newsletter'
    end
    member do
      put 'accept'
      put 'reject'
      put 'unsuspend'
      put 'suspend'
    end
    resources :salaries, :singular => 'salarie'
    resources :locals
    resources :besoin_humains
    resources :besoin_materiels
    resources :activites
    resources :regroupements
    resources :dispositifs
    resources :agrements
    resources :orgahabs
    resources :adhesions
    resources :assoc_manifs
    resources :manifestations
    resources :assoc_champintervs
    resources :champ_interventions
    resources :membres
    resources :conseiladmins
    resources :conv_pluris
  end
  
  resources :conseiladmins do
    resources :presidents
    resources :premier_vicepresidents
    resources :second_vicepresidents
    resources :secretaires
    resources :secretaire_adjoints
    resources :tresoriers
    resources :tresorier_adjoints
    resources :membres
  end
  
  resources :regroupements

  resources :agrements

  resources :orgahabs do
    resources :agrements
    resources :conv_pluris
  end

  resources :adhesions

  resources :assoc_manifs

  resources :membres

  resources :manifestations do
    resources :associations
  end

  resources :champ_interventions

  resources :salaries, :singular => 'salarie'

  resources :activites do
    resources :plannings
  end

  resources :besoin_materiels
  
  resources :besoin_humains
  
  resources :locals
  
  resources :users
    

  resource :recherches do
    collection do
      get 'liste'
      post 'commune'
      get 'export_result'
      get 'export_excel'
    end
  end

  match '/recherch/:id' => 'recherches#show', :as => 'recherch'
   
  match '/demande_abonnement', :controller => 'associations', :action => 'form_abonnement'
  
  
  

  root :to => 'associations#accueil'

  match ':controller/service.wsdl', :action => 'wsdl'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/newsletter.rb
# -*- encoding : utf-8 -*-
class Newsletter < ActiveRecord::Base
  has_many :nl_contents
  
  def deliver
    #find all the abonnes emails
    @abonnes = Abonne.all.collect(&:email)
    # Sends the newsletter to each one
    @abonnes.each do |abonne|
      NewsletterMailer.deliver_newsletter(abonne, self)
    end
    # Set the delivered_at time to now
    self.update_attribute(:delivered_at, Time.now)
  end
end

app/controllers/newsletters_controller.rb
# -*- encoding : utf-8 -*-
class NewslettersController < ApplicationController
  before_filter :login_required
  
  # def deliver
  #   call_rake(:send_newsletter, :newsletter_id => params[:id].to_i)
  #   flash[:notice] = "En cours d'envoi"
  #   redirect_to newsletters_url
  # end
  
  def deliver
    @newsletter = Newsletter.find(params[:id])
    @newsletter.send_later(:deliver)
    flash[:notice] = "Newsletter en cours d'envoi …"
    redirect_to(newsletters_url)
  end
  
  def desabonnement
  end
  
  def delete_abonne
    @abonne = Abonne.find_by_email_abonne(params[:email])
    respond_to do |format|
      if !@abonne.nil?
        @abonne.destroy
        flash[:notice] = "Vous n'êtes plus abonnés à la lettre d'information"
        format.html { redirect_to desabonnement_newsletters_url }
      else
        flash[:notice] = "Cette adresse email n'existe pas dans notre base"
        format.html { redirect_to desabonnement_newsletters_url }
      end
    end
  end
  
  # GET /newsletters
  # GET /newsletters.xml
  def index
    @newsletters = Newsletter.paginate(:page => params[:page], :per_page => 20,
     :order => "created_at DESC, date_pub DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @newsletters }
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.xml
  def show
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @newsletter }
    end
  end

  # GET /newsletters/new
  # GET /newsletters/new.xml
  def new
    @newsletter = Newsletter.new
    @contenu_nls = []
    2.times { @contenu_nls << NlContent.new }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @newsletter }
    end
  end

  # GET /newsletters/1/edit
  def edit
    @newsletter = Newsletter.find(params[:id])
    @contenu_nls = @newsletter.nl_contents
  end

  # POST /newsletters
  # POST /newsletters.xml
  def create
    @newsletter = Newsletter.new(params[:newsletter])

    respond_to do |format|
      if @newsletter.save
        flash[:notice] = 'Newsletter créée avec succès.'
        format.html { redirect_to(@newsletter) }
        format.xml  { render :xml => @newsletter, :status => :created, :location => @newsletter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @newsletter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /newsletters/1
  # PUT /newsletters/1.xml
  def update
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      if @newsletter.update_attributes(params[:newsletter])
        flash[:notice] = 'Newsletter was successfully updated.'
        format.html { redirect_to(@newsletter) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @newsletter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.xml
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to(newsletters_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/newsletters/_contenu_nl.html.erb
<div class="article">
  <% fields_for "newsletter[contenu_nl_attributes][]", contenu_nl do |article| %>
  <table>
    <tr>
      <th>Titre :</th>
      <td><%= article.text_field :titre, :size => 70, :index => nil %></td>
    </tr>
    <tr>
      <th>Contenu :</th>
      <td><%= article.text_area :body, :cols => 70, :rows => 10, :index => nil %></td>
    </tr>
  </table>
    <% if contenu_nl.new_record? %>
  		<%= link_to_function "supprimer", "this.up('.article').remove()" %>
  	<% else %>
  		<%= link_to_function "supprimer", "mark_article_for_destroy(this)" %>
  		<%= article.hidden_field :id, :index => nil %>
  		<%= article.hidden_field :should_destroy, :index => nil, :class => 'should_destroy' %>
  	<% end %>
  <% end %>

</div>

app/views/newsletters/desabonnement.html.erb
<div id="colonne1">
  <h2 class="ficheid">Désabonnement à notre Newsletter</h2>

  <p>
    Entrez l'adresse email à laquelle vous recevez notre lettre d'information pour vous désinscrire.
  </p>

  <p>
    <% form_tag delete_abonne_newsletters_path(), {:method => :put} do %>
      Votre Email : <%= text_field_tag :email %>
    
      <%= submit_tag "Désabonner" %>
    <% end %>
  </p>
</div>

<div id="side-colonne">
	<%= render :partial => "shared/sidecolonne2" %>
	<div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p>
			<b>Partenaires :</b>
		</p>
		<p>
			<a href="http://www.club1901.asso.fr" class="image">
			<img src="/images/Logo-club1901.gif"
			border="0" alt="logo-club1901"></a>
		</p>
		<p>
			<a href="#" class="image">
			<img src="/images/Logo-agouti.gif"
			border="0" alt="logo-agouti"></a>
		</p>
		<p>
			<a href="#" class="image">
			<img src="/images/Logo-crajep.gif"
			border="0" alt="logo-agouti"></a>
		</p>
	</div>
</div>

app/views/newsletters/edit.html.erb
<div id="side-colonne">
  <div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></p>
		<p>
			<b>Recherche rapide</b><br/>
			<% form_tag associations_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %><br/><br/>
				<%= submit_tag "Trouver", :name => nil %>
			<% end %>
		</p>
		<p class="to_valid">
			À valider : <%= @nb_to_verify %><br/>
			<%= validation_links(@nb_to_verify) %>
		</p>
		<p><%= link_to 'Ajouter une association', new_association_path %></p>
		<% unless @last_recorded.nil? %>
		<p>
			Dernière association reférencée :<br/>
			<%= link_to  @last_recorded.nom, association_path(@last_recorded)  %><br/>
			le <%= h @last_recorded.created_at.strftime("%d/%m/%Y") %>
		</p>
		<% end %>
		<p>
			Nombre d'associations enregistrées : <strong><%=h Association.count %></strong><br/>
		</p>
		<p class="export_csv">
			<%= link_to "Export Excel", formatted_export_xls_csv_associations_url(:xls) %><br/>
			<%= link_to "Export CSV", formatted_export_xls_csv_associations_url(:csv) %><br/>
			<%= link_to "Gestion des Mailings", mailings_path() %><br/>
			<%= link_to "Gestion des Newsletters", newsletters_path() %>
		</p>
		<p class="to_valid">
			Assos incomplètes : <%= @asso_incomplete %><br/>
			<%= link_to "Voir", incomplete_associations_path() %>
		</p>
		<p>
			<%= link_to "Ajouter un champ d'intervention", new_champ_intervention_path() %>
		</p>
	</div>
</div>

<div id="colonne1">
  <h2 class="ficheid">Modifier une Newsletter</h2>

  <%= error_messages_for :newsletter %>

  <% form_for(@newsletter) do |f| %>
    <p>
      <b>Date pub</b><br />
      <%= f.date_select :date_pub %>
    </p>
  
    <fieldset>
      <legend><b>Articles de la Newsletter</b></legend>
      <div id="articles">
        <%= render :partial => "contenu_nl", :collection => @contenu_nls %>
      </div>
      <%= lien_ajout_article "Ajouter un article" %>
    </fieldset>

    <p>
      <%= f.submit "Mettre à jour" %>
    </p>
  <% end %>

  <%= link_to 'Voir', @newsletter %> |
  <%= link_to 'Retour', newsletters_path %>
</div>

app/views/newsletters/index.html.erb
<div id="side-colonne">
  <div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></p>
		<p>
			<b>Recherche rapide</b><br/>
			<% form_tag associations_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %><br/><br/>
				<%= submit_tag "Trouver", :name => nil %>
			<% end %>
		</p>
		<p class="to_valid">
			À valider : <%= @nb_to_verify %><br/>
			<%= validation_links(@nb_to_verify) %>
		</p>
		<p><%= link_to 'Ajouter une association', new_association_path %></p>
		<% unless @last_recorded.nil? %>
		<p>
			Dernière association reférencée :<br/>
			<%= link_to  @last_recorded.nom, association_path(@last_recorded)  %><br/>
			le <%= h @last_recorded.created_at.strftime("%d/%m/%Y") %>
		</p>
		<% end %>
		<p>
			Nombre d'associations enregistrées : <strong><%=h Association.count %></strong><br/>
		</p>
		<p class="export_csv">
			<%= link_to "Export Excel", formatted_export_xls_csv_associations_url(:xls) %><br/>
			<%= link_to "Export CSV", formatted_export_xls_csv_associations_url(:csv) %><br/>
			<%= link_to "Gestion des Mailings", mailings_path() %><br/>
			<%= link_to "Gestion des Newsletters", newsletters_path() %>
		</p>
		<p class="to_valid">
			Assos incomplètes : <%= @asso_incomplete %><br/>
			<%= link_to "Voir", incomplete_associations_path() %>
		</p>
		<p>
			<%= link_to "Ajouter un champ d'intervention", new_champ_intervention_path() %>
		</p>
	</div>
</div>

<div id="colonne1">
  <h2 class="ficheid">Listing des Newsletters</h2>

  <table>
    <tr>
      <th>Date Publication</th>
      <th>Numero</th>
    </tr>

  <% for newsletter in @newsletters %>
    <tr>
      <td><%=h newsletter.date_pub.strftime("%d/%m/%Y") %></td>
      <td><%=h newsletter.numero %></td>
      <td><%= link_to 'Voir', newsletter %></td>
      <td><%= link_to 'Modifier', edit_newsletter_path(newsletter) %></td>
      <td><%= link_to 'Supprimer', newsletter, :confirm => 'Are you sure?', :method => :delete %></td>
      <td><%= link_to 'Envoyer', deliver_newsletter_path(newsletter) %></td>
    </tr>
  <% end %>
  </table>

  <br />
  <%= will_paginate @newsletter %>

  <%= link_to 'Nouvelle Newsletter', new_newsletter_path %>
</div>

app/views/newsletters/new.html.erb
<div id="side-colonne">
  <div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></p>
		<p>
			<b>Recherche rapide</b><br/>
			<% form_tag associations_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %><br/><br/>
				<%= submit_tag "Trouver", :name => nil %>
			<% end %>
		</p>
		<p class="to_valid">
			À valider : <%= @nb_to_verify %><br/>
			<%= validation_links(@nb_to_verify) %>
		</p>
		<p><%= link_to 'Ajouter une association', new_association_path %></p>
		<% unless @last_recorded.nil? %>
		<p>
			Dernière association reférencée :<br/>
			<%= link_to  @last_recorded.nom, association_path(@last_recorded)  %><br/>
			le <%= h @last_recorded.created_at.strftime("%d/%m/%Y") %>
		</p>
		<% end %>
		<p>
			Nombre d'associations enregistrées : <strong><%=h Association.count %></strong><br/>
		</p>
		<p class="export_csv">
			<%= link_to "Export Excel", formatted_export_xls_csv_associations_url(:xls) %><br/>
			<%= link_to "Export CSV", formatted_export_xls_csv_associations_url(:csv) %><br/>
			<%= link_to "Gestion des Mailings", mailings_path() %><br/>
			<%= link_to "Gestion des Newsletters", newsletters_path() %>
		</p>
		<p class="to_valid">
			Assos incomplètes : <%= @asso_incomplete %><br/>
			<%= link_to "Voir", incomplete_associations_path() %>
		</p>
		<p>
			<%= link_to "Ajouter un champ d'intervention", new_champ_intervention_path() %>
		</p>
	</div>
</div>

<div id="colonne1">
  <h2 class="ficheid">Création d'une Newsletter</h2>

  <%= error_messages_for :newsletter %>

  <% form_for(@newsletter) do |f| %>
 
    <fieldset>
      <legend><b>Articles de la Newsletter</b></legend>
      <div id="articles">
        <%= render :partial => "contenu_nl", :collection => @contenu_nls %>
      </div>
      <%= lien_ajout_article "Ajouter un article" %>
    </fieldset>

    <p>
      <%= f.submit "Enregistrer" %>
    </p>
  <% end %>

  <%= link_to 'Retour', newsletters_path %>
</div>

app/views/newsletters/show.html.erb
<div id="side-colonne">
  <div class="topsidemenu">
		&nbsp;		
	</div>
	<div class="side-menu">
		<p><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></p>
		<p>
			<b>Recherche rapide</b><br/>
			<% form_tag associations_path, :method => 'get' do %>
				<%= text_field_tag :search, params[:search] %><br/><br/>
				<%= submit_tag "Trouver", :name => nil %>
			<% end %>
		</p>
		<p class="to_valid">
			À valider : <%= @nb_to_verify %><br/>
			<%= validation_links(@nb_to_verify) %>
		</p>
		<p><%= link_to 'Ajouter une association', new_association_path %></p>
		<% unless @last_recorded.nil? %>
		<p>
			Dernière association reférencée :<br/>
			<%= link_to  @last_recorded.nom, association_path(@last_recorded)  %><br/>
			le <%= h @last_recorded.created_at.strftime("%d/%m/%Y") %>
		</p>
		<% end %>
		<p>
			Nombre d'associations enregistrées : <strong><%=h Association.count %></strong><br/>
		</p>
		<p class="export_csv">
			<%= link_to "Export Excel", formatted_export_xls_csv_associations_url(:xls) %><br/>
			<%= link_to "Export CSV", formatted_export_xls_csv_associations_url(:csv) %><br/>
			<%= link_to "Gestion des Mailings", mailings_path() %><br/>
			<%= link_to "Gestion des Newsletters", newsletters_path() %>
		</p>
		<p class="to_valid">
			Assos incomplètes : <%= @asso_incomplete %><br/>
			<%= link_to "Voir", incomplete_associations_path() %>
		</p>
		<p>
			<%= link_to "Ajouter un champ d'intervention", new_champ_intervention_path() %>
		</p>
	</div>
</div>

<div id="colonne1">
  <h2 class="ficheid">Voir Newsletter</h2>
  <p>
    <b>Date publication :</b>
    <% if @newsletter.date_pub %>
      <%= h @newsletter.date_pub.strftime("%d/%m/%Y") %>
    <% else %>
      Pas encore publié.
    <% end %>
  </p>

  <p>
    <b>Numero:</b>
    <%=h @newsletter.numero %>
  </p>
  
  <% @newsletter.nl_contents.each do |content| %>
  <p>
    <b><%= content.titre %></b><br/>
  </p>
  <p>
    <%= simple_format(content.body) %>
  </p>
  <% end %>


  <%= link_to 'Modifier', edit_newsletter_path(@newsletter) %> |
  <%= link_to 'Retour', newsletters_path %>
</div>